### PR TITLE
Add Jira command set

### LINKED ISSUE #130: Jira command-set
We need the jira command-set to demo it to Uber on Slack. We can implement some of the commands which are supported by [jira-mattermost-plugin](https://mattermost.gitbook.io/plugin-jira/feature-summary)

### PR DESCRIPTION
**Pull request by satyarohith**
This PR includes the following commands:
- `jira`
- `jira_create_issue`
- `jira_assign_issue`
- `jira_transition`

Closes #130

### CODE REVIEW

**Review by bhageena — APPROVED** [review]
lgtm

**Comment by niks3089** [comment]
LGTM. Can you add just `jira` command to fetch and print the README? I think this is done for gitlab

**Comment by satyarohith** [comment]
Sure

**Comment by satyarohith** [comment]
.@niks3089 I just pushed `jira` command.

**Review by niks3089 — APPROVED** [review]

**Pull request merged**
