### PR TITLE
Add cured data

### PR DESCRIPTION
**Pull request by bhageena**

### CODE REVIEW

**Review by satyarohith — COMMENTED** [review]
LGTM. A screenshot would be really helpful. :)

**Comment by bhageena** [comment]
> LGTM. A screenshot would be really helpful. :)

Screenshot from 2020-02-03 20-06-15

**Comment by rabbah** [comment]
is it possible to show cases per country (as an optional flag)?

**Comment by bhageena** [comment]
> is it possible to show cases per country (as an optional flag)?

sure, the `country` command takes country_name as an option

e.g.  `/ncovstats country india`

**Comment by rabbah** [comment]
Awesome. Thanks!

**Pull request merged**
