### PR TITLE
Add command sets for getting coronaviruses stats

### PR DESCRIPTION
**Pull request by bhageena**

### CODE REVIEW

**Comment by bhageena** [comment]
It's nor for mattermost yet.

**Comment by niks3089** [comment]
Interesting. Can you share some screenshots please?

**Comment by bhageena** [comment]
> Interesting. Can you share some screenshots please?

Screenshot from 2020-02-02 19-13-41

**Review by niks3089 — APPROVED** [review]
LGTM. I will wait for Satya to see if he has any comments.

**Comment by satyarohith** [comment]
LGTM. Pretty useful commands! 👏

**Review by satyarohith — APPROVED** [review]

**Pull request merged**
